name: Build

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    
env:
  BUILD_SH: build.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Get REPO Name'
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | sed 's/WE1ZARD\///')" >> $GITHUB_ENV

    - name: Get Version
      run: |
        echo "version=$(sed -n 1p ./update_log.md | sed "s/##\s${{env.REPO}}\s//")" >> $GITHUB_ENV

    - name: 'Pack'
      run: |
        cd ./CN
        mv ./switch/DBI/dbi.config ./switch/DBI/dbi.config.template
        zip -rq9 ${{env.REPO}}_${{env.version}}_CN.zip ./switch
        cd ../EN
        mv ./switch/DBI/dbi.config ./switch/DBI/dbi.config.template
        zip -rq9 ${{env.REPO}}_658_EN.zip ./switch
        cd ../RU
        mv ./switch/DBI/dbi.config ./switch/DBI/dbi.config.template
        zip -rq9 ${{env.REPO}}_${{env.version}}_RU.zip ./switch

    - name: 'Upload'
      run: |
        mv ./update_log.md ./更新日志.md
        curl -T '{更新日志.md,./CN/${{env.REPO}}_${{env.version}}_CN.zip}' -u ${{ secrets.WEBDAV_TOKEN }} 'https://dav.jianguoyun.com/dav/switch/${{env.REPO}}/'
        mv ./CN/${{env.REPO}}_${{env.version}}_CN.zip ./${{env.REPO}}_CN.zip
        mv ./EN/${{env.REPO}}_658_EN.zip ./${{env.REPO}}_EN.zip
        mv ./RU/${{env.REPO}}_${{env.version}}_RU.zip ./${{env.REPO}}_RU.zip

    - name: 'Release'
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
      with:
        draft: false
        tag_name: 'latest'
        files: |
          ./${{env.REPO}}_CN.zip
          ./${{env.REPO}}_EN.zip
          ./${{env.REPO}}_RU.zip