name: Build

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    
env:
  BUILD_SH: build.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get REPO Name
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | sed 's/WE1ZARD\///')" >> $GITHUB_ENV

    - name: Get Version
      run: |
        echo "version=$(sed -n 1p ./update_log.md | sed "s/##\s//")" >> $GITHUB_ENV

    - name: Pack
      run: |
        cd ./CN
        zip -rq ${{env.REPO}}_647_CN.zip ./switch
        cd ../EN
        zip -rq ${{env.REPO}}_658_EN.zip ./switch
        cd ../RU
        zip -rq ${{env.REPO}}_${{env.version}}_RU.zip ./switch

    - name: Upload
      run: |
        curl -T '{./RU/${{env.REPO}}_${{env.version}}_RU.zip,update_log.md}' -u ${{ secrets.WEBDAV_TOKEN }} 'https://dav.jianguoyun.com/dav/switch/${{env.REPO}}/'
        mv ./RU/${{env.REPO}}_${{env.version}}_RU.zip ./${{env.REPO}}_RU.zip
        
    - name: Release
      uses: softprops/action-gh-release@master
      with:
        draft: false
        tag_name: 'latest'
        files: |
          ./CN/${{env.REPO}}_647_CN.zip
          ./EN/${{env.REPO}}_658_EN.zip
          ./${{env.REPO}}_RU.zip